### ISSUE TITLE
Issues in connection 

### ISSUE THREAD

**Issue by shiv71** [blikoon/Rooster#4]
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed:

in  builder.setServiceName(""); this line. I have pass Server Name and Host Name of open fire server but not work how to solve this reply pls

Thanks.

**Comment by xyzizix** [comment]
Please use an account from a server you know is working fine.I have suggested a few of those in the tutorial http://www.blikoon.com/tutorials/android-smack-xmpp-introductionbuilding-a-simple-client

**Comment by rutura** [comment]
Please use an account from a server you know to be working and just do normal login.I have suggested a few servers in the tutorial http://www.blikoon.com/tutorials/android-smack-xmpp-introductionbuilding-a-simple-client
