### ISSUE TITLE
cANT Connect to server

### ISSUE THREAD

**Issue by lordmen99** [blikoon/Rooster#5]
Please fixt again, first i compile and run, its can connect to server and chat. after that cant connect

**Comment by androwed** [comment]
Yes, there is a problem in reconnection. Even restarting app does not reconnect and stuck on onStartCommand() --> start() function in RoosterConnectionService.java, Thread-->  if( mThread ==null || !mThread.isAlive()) condition is not validated and the thread is not started (as in my case).

**Comment by rutura** [comment]
This is just a tutorial guys . Not a regular xmpp client you use daily. Re connection and other issues are out of scope of the tutorial. You can read further in smack docs/xmpp standards and implement these in your own forks.

**Comment by androwed** [comment]
@rutura Hi, do you have any ideas ? or implementations or any suggestions on re-connection or sustaining the connection.
